players = [
    { "name": "Lionel Messi", "team": "Paris Saint-Germain", "goals": 27, "assists": 18 },
    { "name": "Cristiano Ronaldo", "team": "Al Nassr", "goals": 30, "assists": 5 },
    { "name": "Kylian Mbappé", "team": "Paris Saint-Germain", "goals": 25, "assists": 7 },
    { "name": "Neymar Jr", "team": "Paris Saint-Germain", "goals": 15, "assists": 12 },
    { "name": "Mohamed Salah", "team": "Liverpool", "goals": 23, "assists": 10 },
    { "name": "Erling Haaland", "team": "Manchester City", "goals": 35, "assists": 4 },
    { "name": "Robert Lewandowski", "team": "Barcelona", "goals": 27, "assists": 6 },
    { "name": "Harry Kane", "team": "Bayern Munich", "goals": 28, "assists": 5 },
    { "name": "Kevin De Bruyne", "team": "Manchester City", "goals": 6, "assists": 16 },
    { "name": "Luka Modrić", "team": "Real Madrid", "goals": 5, "assists": 7 },
    { "name": "Vinícius Júnior", "team": "Real Madrid", "goals": 21, "assists": 10 },
    { "name": "Karim Benzema", "team": "Al-Ittihad", "goals": 18, "assists": 7 },
    { "name": "Sadio Mané", "team": "Al Nassr", "goals": 16, "assists": 8 },
    { "name": "Thibaut Courtois", "team": "Real Madrid", "goals": 0, "assists": 0 },
    { "name": "Jan Oblak", "team": "Atletico Madrid", "goals": 0, "assists": 0 },
    { "name": "Marc-André ter Stegen", "team": "Barcelona", "goals": 0, "assists": 0 },
    { "name": "Gianluigi Donnarumma", "team": "Paris Saint-Germain", "goals": 0, "assists": 0 },
    { "name": "Alisson Becker", "team": "Liverpool", "goals": 1, "assists": 0 },
    { "name": "Trent Alexander-Arnold", "team": "Liverpool", "goals": 5, "assists": 15 },
    { "name": "Virgil van Dijk", "team": "Liverpool", "goals": 8, "assists": 2 },
    { "name": "Ruben Dias", "team": "Manchester City", "goals": 4, "assists": 1 },
    { "name": "Mohamed Elneny", "team": "Arsenal", "goals": 2, "assists": 4 },
    { "name": "Gonzalo Higuaín", "team": "Retired", "goals": 35, "assists": 15 },
    { "name": "Marcelo", "team": "Fluminense", "goals": 7, "assists": 8 },
    { "name": "João Félix", "team": "Chelsea", "goals": 10, "assists": 6 },
    { "name": "Vinícius Júnior", "team": "Real Madrid", "goals": 21, "assists": 10 },
    { "name": "Sergio Ramos", "team": "Paris Saint-Germain", "goals": 7, "assists": 3 },
    { "name": "David Silva", "team": "Real Sociedad", "goals": 3, "assists": 7 },
    { "name": "Zlatan Ibrahimović", "team": "Retired", "goals": 500, "assists": 200 },
    { "name": "Marco Reus", "team": "Borussia Dortmund", "goals": 10, "assists": 8 },
    { "name": "Jadon Sancho", "team": "Manchester United", "goals": 9, "assists": 5 },
    { "name": "Paulo Dybala", "team": "AS Roma", "goals": 15, "assists": 9 },
    { "name": "Angel Di María", "team": "Benfica", "goals": 6, "assists": 10 },
    { "name": "Jack Harrison", "team": "Leeds United", "goals": 8, "assists": 7 },
    { "name": "Declan Rice", "team": "Arsenal", "goals": 6, "assists": 5 },
    { "name": "Timo Werner", "team": "RB Leipzig", "goals": 14, "assists": 5 },
    { "name": "Christian Pulisic", "team": "Chelsea", "goals": 6, "assists": 8 },
    { "name": "Giovani Lo Celso", "team": "Villarreal", "goals": 5, "assists": 6 },
    { "name": "Ciro Immobile", "team": "Lazio", "goals": 20, "assists": 5 },
    { "name": "Dries Mertens", "team": "Galatasaray", "goals": 13, "assists": 9 },
    { "name": "Mauro Icardi", "team": "Galatasaray", "goals": 22, "assists": 7 },
    { "name": "Hugo Lloris", "team": "Tottenham Hotspur", "goals": 0, "assists": 0 },
    { "name": "Pierre-Emerick Aubameyang", "team": "Chelsea", "goals": 11, "assists": 5 },
    { "name": "Eden Hazard", "team": "Real Madrid", "goals": 7, "assists": 6 },
    { "name": "Gareth Bale", "team": "Retired", "goals": 50, "assists": 30 },
    { "name": "Nicolas Pépé", "team": "Arsenal", "goals": 12, "assists": 6 },
    { "name": "James Rodríguez", "team": "Al Rayyan", "goals": 6, "assists": 7 },
    { "name": "Luis Suárez", "team": "Grêmio", "goals": 12, "assists": 4 },
    { "name": "André Onana", "team": "Manchester United", "goals": 0, "assists": 0 }
]
fd
